### ISSUE TITLE
Numerous test failures with py3.8.2 (exception messages changed?)

### ISSUE THREAD

**Issue by mgorny** [davidhalter/parso#103]
For example:

```
==================================================================== FAILURES =====================================================================
_________________________________________________ test_python_exception_matches[(lambda: x := 1)] _________________________________________________

code = '(lambda: x := 1)'

    @pytest.mark.parametrize('code', FAILING_EXAMPLES)
    def test_python_exception_matches(code):
        wanted, line_nr = _get_actual_exception(code)
    
        errors = _get_error_list(code)
        actual = None
        if errors:
            error, = errors
            actual = error.message
>       assert actual in wanted
E       AssertionError: assert 'SyntaxError: cannot use named assignment with lambda' in ['SyntaxError: cannot use assignment expressions with lambda']

test/test_python_errors.py:39: AssertionError
```

If I'm looking correctly, all tests failures have the same error.

Full log: [dev-python:parso-0.6.2:20200227-151454.log](https://github.com/davidhalter/parso/files/4262356/dev-python.parso-0.6.2.20200227-151454.log)

**Comment by davidhalter** [comment]
I'll probably wait for a bit until travis has the same output and will then "fix" this. IMO this is not really a bug, because both messages are perfectly fine. It's much more important that we have a CI that's passing.

**Comment by blueyed** [comment]
I've created https://github.com/davidhalter/parso/pull/104.

It would make sense for the tests to pass with both variants though.

**Comment by mgorny** [comment]
I agree. Gentoo is running tests when building packages, so we'd really prefer if tests passed both for users who have upgraded to 3.8.2 already and for those who haven't yet.

**Comment by davidhalter** [comment]
> It would make sense for the tests to pass with both variants though.

It would probably make sense, but it's a waste of time to implement that stuff. For Gentoo, disable all the error tests. They are very susceptible to failures and might break from time to time.

**Comment by blueyed** [comment]
@mgorny 
A PR to un-harden the tests would be still appreciated though I guess - checking for both possible error messages.  IIRC there is a list being used there though already.
@davidhalter 
Please ACK if that makes sense.

**Comment by davidhalter** [comment]
@blueyed I know that this might be wanted by some people, but I'd rather not have it and then later remove it again. Because now it takes a few months and then everyone is using 3.8.2. So I'm not really willing to merge something like that.
