### ISSUE TITLE
Python 3.10+ support?

### ISSUE THREAD

**Issue by carljm** [davidhalter/parso#106]
This is an early-warning issue; just wanted to note that PEP 617 was accepted (https://www.python.org/dev/peps/pep-0617/), meaning that the default parser in Python 3.9 will be a new PEG parser instead of the LL(1) pgen2 parser. By Python 3.10, there could be new syntax added to Python which is not parsable with an LL(1) parser.

I'm curious about parso's plans to support Python 3.10+ in part because I'm updating the Python docs to deprecate `lib2to3` (see https://bugs.python.org/issue40360), and would like to link to maintained alternatives outside the standard library, but only if they plan to update to support Python 3.10+.

**Comment by davidhalter** [comment]
Thanks for bringing this up!

> but only if they plan to update to support Python 3.10+.

I guess to make Jedi work in the future, we will need a proper Python 3.10+ parser. So yes there will be support, but in a first step it will probably still be LL(1).

Parso already doesn't have the exact same grammar as the official Python (for error recovery cases and f-strings, which are part of the grammar and don't require multiple passes). So I'm pretty confident that we can work around a lot of cases.

The first obvious mechanism that will probably be used by a different grammar is `"test '=' test"` (see Grammar file, there's a note about ambiguity in there). However parso already handles that and I guess we can also handle more of these kind of cases. The result is just a syntax tree that is a bit uglier than it could be.

So I doubt that 3.10 will bring a ton of new features that are totally incompatible with an LL(1) parser. We'll see what it brings, but I want to keep Jedi working, so I will have to do something anyway.

**Comment by davidhalter** [comment]
Closing, because there should be 3.10+ support.
