### ISSUE TITLE
Dump parso parse tree

### ISSUE THREAD

**Issue by isidentical** [davidhalter/parso#113]
Is there a way to dump the parse tree of parso, just like `ast.dump`?

**Comment by davidhalter** [comment]
At the moment there is just pickle. There's no other format for now (and I'm not sure there should be, because it would basically be all slow).

**Comment by isidentical** [comment]
> At the moment there is just pickle. There's no other format for now (and I'm not sure there should be, because it would basically be all slow).

I meant dumping as in printing the screen a visual tree, just like [this](https://github.com/python/cpython/blob/master/Tools/peg_generator/pegen/grammar_visualizer.py).

**Comment by davidhalter** [comment]
Ah, ok. I never really thought about this or needed it.

I would be fine adding it, we would just need to come up with a good formatting and a concise method name.

**Comment by gousaiyang** [comment]
Implemented in #187.
