### ISSUE TITLE
GenExp in class bases

### ISSUE THREAD

**Issue by isidentical** [davidhalter/parso#122]
```
>>> get_errors("class X(base for base in bases): pass")
[]
>>> class X(base for base in bases): pass
... 
  File "<stdin>", line 1
SyntaxError: invalid syntax
```

**Comment by davidhalter** [comment]
Just because I'm interested: Where does this error come from? It's the "default" syntax error message, so it's probably not from the ast step, but where is it defined?

**Comment by isidentical** [comment]
> Just because I'm interested: Where does this error come from? It's the "default" syntax error message, so it's probably not from the ast step, but where is it defined?

If I am not mistaken, this should be where it got raised
https://github.com/python/cpython/blob/3436f5f899f272d7164add072beb18eebd46d777/Python/ast.c#L2933-L2935

**Comment by isidentical** [comment]
I'll tinker with the grammar and try to propose a proper error message for this case on the upstream.

**Comment by isidentical** [comment]
The idea got rejected since it would complicate the grammar for a super-rare case. https://github.com/python/cpython/pull/20360
