### ISSUE TITLE
Providing a built-in Cython Grammar

### ISSUE THREAD

**Issue by isidentical** [davidhalter/parso#134]
Cython is well known and a well-used extension/superset of python which uses a slightly extended grammar, but similar. They [already have](https://github.com/cython/cython/blob/master/Cython/Parser/Grammar) a grammar that can be parsed by pgen2. The real question is that would it benefit the Jedi / or any other client of this library to have a first-class support for it?

**Comment by davidhalter** [comment]
I will definitely not support it with Jedi. I simply would like to have time for other projects, so this is not going to be supported in there :) If it's just the grammar, I would be fine adding it, if the tokenizer also needs changes, I'm not sure I would do it.

At the same time the question is if this shouldn't live outside of parso. We could of course document how people could use it.

IMO we should probably wait until we know more about how the pegen stuff works out in Python. But feel free to propose changes, this is just my opinion.

**Comment by bgw** [comment]
> They already have a grammar that can be parsed by pgen2.

My understanding is that the grammar file is missing stuff. It hasn't had any significant changes made to it in 5 years. I think [this is the parser they actually use](https://github.com/cython/cython/blob/master/Cython/Compiler/Parsing.py).

**Comment by isidentical** [comment]
> My understanding is that the grammar file is missing stuff. It hasn't had any significant changes made to it in 5 years. I think this is the parser they actually use.

Thanks, @bgw, looks like you're right. After a bit of thinking, and after noticing that we need to write the grammar ourselves (rather than just copying a suitable grammar) I decided to close this issue.
