### ISSUE TITLE
Internal type annotations?

### ISSUE THREAD

**Issue by PeterJCLaw** [davidhalter/parso#144]
Would there be interest in adding type annotations within parso?

I realise the codebase currently supports Python 2.7 still, which would complicate things a bit, though I think this could help both catch some errors and also make it a bit easier for newcomers to navigate the code.

This feels like it could help with type annotating Jedi (discussion at https://github.com/davidhalter/jedi/issues/1533).

**Comment by davidhalter** [comment]
There are already stubs. I'm going to remove Python 2 support very soon, at that point the stubs can just be removed and type annotations can be used instead.

**Comment by isidentical** [comment]
@davidhalter maybe we should start a roadmap issue about our migration for dropping off 2/3.5 support and like maybe the PEG parser itself?

**Comment by PeterJCLaw** [comment]
Ah, I'd not spotted the stubs.

From the perspective of #1533, the stubs are fine if you're happy with the information they contain -- all that's needed is to expose them to others by adding a `py.typed` file in the right place. Would a PR for that be useful?

**Comment by davidhalter** [comment]
Sure :)

**Comment by davidhalter** [comment]
@isidentical I will drop support for Python 2 in the next few weeks. The PEG parser is something anyone can start at any point :).

I'm just telling you guys that it's going to be very hard to replace the diff parser. I'm probably not going to write a PEG parser in Python if I don't have to. And with that I mean that I would only write one if it was really really needed in Python 3.10+.

**Comment by PeterJCLaw** [comment]
I'm happy to call this fixed by #145.
