### ISSUE TITLE
Version 0.8.0 doesn't work correctly with ipython auto-complete methods

### ISSUE THREAD

**Issue by erykoff** [davidhalter/parso#148]
I was having some issues with `ipython` (latest) 7.17 autocomplete, namely that it could not expand methods in modules/classes, and I tracked it down to `parso=0.8.0`.  In particular, to see the problem:

```
conda create -c conda-forge -n ipy717 ipython=7.17 numpy
```
(As of August 13th, this will install `parso=0.8.0`).

Then after `conda activate ipy171` if you fire up `ipython` and then `import numpy` you can't auto-complete anything in `numpy`.  After running `conda install -c conda-forge parso=0.7` then everything works as expected.

I'm not sure if this is a `parso` problem or an `ipython` problem, however.

**Comment by davidhalter** [comment]
Jedi 0.17.2 is not compatible with parso 0.8.0. Jedi specifies this in its setup.py file as `parso>=0.7.0,<0.8.0`. I wonder: Did you upgrade manually to parso 0.8?

**Comment by davidhalter** [comment]
This is probably a conda problem.

**Comment by erykoff** [comment]
It may be a conda (or conda-forge) problem.  But the default when you install ipython 7.17 gives jedi 0.15.2 and parso 0.8.0, and that's the combination that doesn't work.  Downgrading parso to 0.7.1 appears to fix the issue, but it may not be the unique (or the "correct") solution.

**Comment by davidhalter** [comment]
Yeah, that's unfortunate. If you download an older Jedi version, it was not pinned back then. However I'm still a bit surprised that Jedi 0.15.2 is downloaded. `setup.py` doesn't pin a version: https://github.com/ipython/ipython/blob/7.17.0/setup.py#L190.

In that case conda should download the latest Jedi version, not the old 0.15.2.

**Comment by erykoff** [comment]
If I file a ticket on `conda-forge`, what `jedi` version should be used with `parso=0.8.0`?  Above you say that the latest jedi (0.17.2) is not compatible with parso 0.8.0, which is I think what led the solver to choose an older version, in this case 0.15.2.

**Comment by erykoff** [comment]
Oh, I think I see what is going on.  Although jedi 0.17.2 (and 0.17.1) specifies parso < 0.8.0, jedi previous to that did not.  So from the `conda-forge` perspective, it wanted to install the latest parso (don't know what determines priority), and then it has to go back to a "compatible" jedi version (anything prior to 0.17.1 according to the requirements).  Since no jedi versions have been tagged that are compatible with parso 0.8.0 (as I see is the case in master), then it ends up with a broken installation.  I will file an issue with `conda-forge`, at the very least.

**Comment by davidhalter** [comment]
That makes sense I guess. They probably don't resolve the dependency tree correctly. parso is Jedi's dependency, not IPython's.
