### ISSUE TITLE
conda installs parso 0.8 in python 3.5 environment causing other software to break.

### ISSUE THREAD

**Issue by vik748** [davidhalter/parso#149]
I found this issue when installing spyder 3.3.1 in conda environment with python 3.5 see details at https://github.com/spyder-ide/spyder/issues/13605

Basically, since 0.8 has dropped support for python 3.5, is there a way to adjust compatibilities and requirements so that:
```
conda create -n parso_test python=3.5 parso
```
installs the correct version of parso that would work in that environment.

**Comment by isidentical** [comment]
Our packaging format (in `setup.py`) declares that the minimum python version to run parso 0.8 is `3.6` (both `python_requires` and other classifier tags states that). I guess this is a problem which you should report to whoever packages parso for conda(forge)

**Comment by vik748** [comment]
@isidentical https://anaconda.org/anaconda/parso refers to this repo.  Would you know who packages it?

**Comment by ccordoba12** [comment]
(Spyder maintainer here) @isidentical, you can close this issue if you want. I understand there's nothing you can do about it here.

We're working to give the Anaconda guys a hand with this in another repo.

**Comment by isidentical** [comment]
If it is a public repo, would you mind mentioning me / redirecting me there so that I can see just follow up on the issue? @ccordoba12

**Comment by ccordoba12** [comment]
Done by @dalthviz.

**Comment by isidentical** [comment]
Thanks!

**Comment by davidhalter** [comment]
This is an issue with conda: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/81#issuecomment-675728572
