### ISSUE TITLE
No requirements-dev.txt

### ISSUE THREAD

**Issue by robodair** [davidhalter/parso#15]
I know it's not necessary but it would be a great help when installing sphinx, py.test, pylint, etc when setting up a new clone.

I'd make one but I'm not sure what other dev dependencies should be included.

**Comment by blueyed** [comment]
I would rather go with `extras_require`, e.g. "dev" in `setup.py`.

**Comment by blueyed** [comment]
Added a "testing" extras in #17.

What is "sphinx" required for?
Might be worth an extra "extras", if it is only for building docs.
"tox" does not really make sense there, since it is meant to wrap all of it?!

**Comment by davidhalter** [comment]
sphinx is just required to generate the documentation (make html).

I don't know how you would use that in extras (don't have experience with it).
