### ISSUE TITLE
IPython completion broken by v0.8

### ISSUE THREAD

**Issue by guillaumedlr** [davidhalter/parso#150]
Hi,
First of all, thanks for this amazing package.
On my system (Arch Linux, IPython 7.17.0-1, python-jedi 0.17.0-1 and python-parso 0.8.0-1), the IPython completion for imported modules does not work. For instance
`import pandas as pd

pd.Dat`
and <tab> does not show any completion
Downgrading to python-parso 0.7 solves the issue.

**Comment by isidentical** [comment]
Do you use conda? (See #148 #149 for details)

**Comment by guillaumedlr** [comment]
Thanks for the links. I am not using conda, but this is exactly the same issue with the ipython Arch Linux package. So that was indeed the same issue, thanks for the quick reply.
