### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by hjwp** [davidhalter/parso#153]
Is it maybe extra-hard because Python changed its parser?

**Comment by isidentical** [comment]
We actually support %100 of the 'official' grammar for 3.9 (see #123 for details, we are even fully compatabile with the syntax errors of the new parser)! FWIW There is an 'unofficial' feature of the new parser, that targets 3.10 but also presented in 3.9, which is optional parens on `with` statement.

**Comment by hjwp** [comment]
oh cool!  sorry i didn't see that.  am actually looking for 3.9 support upstream in `jedi-vim`, will take a look there.  maybe i can just update submodules and get it working!

**Comment by hjwp** [comment]
for info: https://github.com/davidhalter/jedi-vim/pull/1029
