### ISSUE TITLE
Parso fails to parse some "unparenthesized" syntactic structures in f-string expression part

### ISSUE THREAD

**Issue by gousaiyang** [davidhalter/parso#158]
Currently `parso` cannot parse the following unparenthesized structures in f-string expression part, which are actually syntactically valid Python code:

- Unparenthesized iterable unpacking in expression lists: `f'{*x,}'`, `f'{*x, *y}'`, `f'{x, *y}'`, `f'{*x, y}'`
- Unparenthesized generator expression: `f'{x for x in [1]}'`
- Unparenthesized yield expression: `def foo(): f'{yield 1}'` (I just saw #157 is already opened for this)

**Comment by isidentical** [comment]
Would you like to submit a patch?

**Comment by gousaiyang** [comment]
Looks like updating the grammar is sufficient to solve the problem, I've created PR #159.

**Comment by davidhalter** [comment]
Thanks @gousaiyang and @isidentical.
