### ISSUE TITLE
"SyntaxError: no binding for nonlocal 'X' found" when X is a parameter

### ISSUE THREAD

**Issue by Terseus** [davidhalter/parso#175]
# Observed behavior

When Jedi finds a function parameter declared as `nonlocal` inside an inner function, the "nonlocal" it's marked wrongly as a syntax error.

For example, given this Python script `poc_nonlocal.py`:
```python
def nonlocal_variable():
    def inner():
        nonlocal value  # No Jedi error here
        print(f"Value before: {value}")
        value = 10
        print(f"Value after: {value}")

    value = 20
    inner()


def nonlocal_parameter(param):
    def inner():
        nonlocal param  # Jedi: SyntaxError: no binding for nonlocal 'param' found
        print(f"Param before: {param}")
        param = 10
        print(f"Param after: {param}")

    inner()


if __name__ == '__main__':
    nonlocal_variable()
    nonlocal_parameter(100)
```

The output shows that both nonlocal directive uses are legal and works as expected:
```
Value before: 20
Value after: 10
Param before: 100
Param after: 10
```

However this exact same code reports a syntax error in Jedi:
```python
import jedi


with open('poc_nonlocal.py', 'r') as f:
    code = f.read()

script = jedi.Script(code=code)
errors = script.get_syntax_errors()
print(errors)
print(errors[0].get_message())
```

Output:
```
[<SyntaxError from=(14, 17) to=(14, 22)>]
SyntaxError: no binding for nonlocal 'param' found
```

# Expected behavior

Jedi shouldn't report a syntax error in a `nonlocal` clause using a method parameter.

# Additional notes

* Python version: 3.9.1
* Jedi version: 0.18.0 (also happens on current master)

At first I tried to write a test in `jedi/test/static_analysis/nonlocal.py` like this:
```python
def nonlocal_variable():
    def inner():
        nonlocal value
        value = 10

    value = 20


def nonlocal_parameter(param):
    def inner():
        nonlocal param
        param = 10
```

I though this would serve as a test for the bug but it doesn't fail when running the test suite, what am I doing wrong in this test?

**Comment by davidhalter** [comment]
> I though this would serve as a test for the bug but it doesn't fail when running the test suite, what am I doing wrong in this test?

Jedi isn't responsible for generating SyntaxErrors. It's therefore also not tested there. I have moved it to the parso issue tracker, where this is definitely right.

It is also probably very possible to fix this yourself. It's not a particularly hard issue. The file that has to be changed is `parso/python/errors.py`.

**Comment by Terseus** [comment]
@davidhalter I've opened a PR that fixes the bug, you were right, it wasn't hard.

Please take a look when you can.

**Comment by davidhalter** [comment]
Sorry I somehow missed it. Thanks for contributing!
