### ISSUE TITLE
Conversion from `parso` to `ast`

### ISSUE THREAD

**Issue by KOLANICH** [davidhalter/parso#180]
AST is blessed and in the standard lib, so it is a standard used by some tools, so it'd be nice to convert from parso AST to ast AST. I.e. it'd allow parsing python 2 from python 3 with parso and process the result with the tools dealing with built-in `ast`.

**Comment by isidentical** [comment]
Having to maintain a CST->AST converter is just terrible. See [this](https://github.com/mozillazg/pypy/blob/py3.8/pypy/interpreter/astcompiler/astbuilder.py) for example. I don't think this is a viable approach. The best you can do is (for the same major version) get the string version and re-parse with ast.

**Comment by KOLANICH** [comment]
1. Does `parso` have serializing capabilities? I haven't found them in the docs.
2. Can they be used to parse python 2 into an AST  and then dump the AST as if it was python 3 (something like 2to3, but without additional refactoring passes and fixes).

>See this for example.

It doesn't look like conversion of CST to AST, it looks more like building AST from tokens. If I understand right, CST is not a parse tree (a low-level structure), it is an AST (a high-level structure) with additional features to store information about details having no effect on behavior.

**Comment by isidentical** [comment]
> It doesn't look like conversion of CST to AST, it looks more like building AST from tokens in a parse tree. If I understand right, CST is not a parse tree (a low-level structure), it is an AST (a high-level structure) with additional features to store information about details having no effect on behavior.

No. It is the conversion of CST to AST. And yes, we need to a very similar code for ourselves.

**Comment by davidhalter** [comment]
> Can they be used to parse python 2 into an AST and then dump the AST as if it was python 3 (something like 2to3, but without additional refactoring passes and fixes).

Why do you want to do that? That sounds like `input == output`.

> Does parso have serializing capabilities? I haven't found them in the docs.

You can serialize any object to string with `get_code()`. Otherwise you can easily serialize it yourself with like 10 lines of code.

**Comment by KOLANICH** [comment]
>Why do you want to do that? That sounds like input == output.

Parsing python 2 code from python 3 into an AST without ability to run this AST (because of lack of other fixes it would likely has issues) is still beneficial, since the AST can be not only run, but also processed without running for purpose of extraction of information. Of course I can run `2to3` on the code first, but it seems that `2to3` and `lib2to3` are going to be dropped and removed. At least [`lib2to3` page](https://docs.python.org/3/library/2to3.html#module-lib2to3) has a recommendation to use `parso` instead.

>You can serialize any object to string with get_code(). Otherwise you can easily serialize it yourself with like 10 lines of code.

Thanks for the info.

**Comment by davidhalter** [comment]
> At least lib2to3 page has a recommendation to use parso instead.

It is very likely that we are going to drop Python 2 soon. It is recommended, because the `lib2to3` parser is not going to support Python 3.10 Syntax. The recommendation has nothing to do with Python 2.

**Comment by KOLANICH** [comment]
Thanks for the info.
