### ISSUE TITLE
Determine if a string could be valid python code

### ISSUE THREAD

**Issue by lukesalamone** [davidhalter/parso#182]
Hi, I would like to write a function to determine if a given string could be the start of valid python code. For example, `x = ` could be the beginning of valid python, even though it is not itself valid python. Can Parso be used to do this? That is, I would like to parse the string from left to right and return `True` if the string could be the beginning of valid python and `False` if it is definitely illegal. For example `def def ` is definitely illegal.

**Comment by gousaiyang** [comment]
You may try something like this:

```python
import parso

code = 'x = '
grammar = parso.load_grammar(version='3.9')
try:
    module = grammar.parse(code, error_recovery=False)
except parso.ParserSyntaxError as e:
    if e.args[1].token_type.name == 'ENDMARKER':
        # possibly start of valid python code
        print('Code ended prematurely')
    else:
        # not start of valid python code
        print('Unacceptable token (other than ENDMARKER) during parsing')
else:
    errors = grammar.iter_errors(module)
    if errors:
        # might be errors during semantic analysis, e.g. 'break' outside loop
        print('Still some errors')
    else:
        print('No errors, good code')
```

**Comment by davidhalter** [comment]
What are you trying to accomplish @lukesalamone ?

**Comment by lukesalamone** [comment]
Thank you! Yes this worked for me.
