### ISSUE TITLE
Documentation on Read the Docs no longer building

### ISSUE THREAD

**Issue by gousaiyang** [davidhalter/parso#190]
When I visit the [`parso` documentation on Read the Docs](https://parso.readthedocs.io/en/latest/), the index page still says "Release v0.7.1", while the latest version at the moment is 0.8.2. Looks like the doc isn't building for recent several months. As the doc builds well in my local environment, I suspect there is a configuration error (e.g. missing webhook) which prevents the doc from building and updating.

**Comment by davidhalter** [comment]
Thanks for bringing this up! I switched the Python version to Python 3 in the readthedocs settings: https://parso.readthedocs.io/en/latest/index.html

Hope this is fine now.
