### ISSUE TITLE
Should star only parameters be parsed to Param?

### ISSUE THREAD

**Issue by namelivia** [davidhalter/parso#191]
Hello! First of all thanks for this piece of code, it is helping me A LOT.
I was wondering if [star-only parameters](https://www.python.org/dev/peps/pep-3102/) should be parsed as an instance of `Param` too, like:

```python
def function_with_mandatory_named_params(param: str, *, kw_param: int):
    pass
```

For my particular use case, it would be very helpful since I'm programmatically going through a big codebase and analyzing the function arguments, and those after the asterisk are the keyword-only ones, so I could identify them by iterating the `get_params()` array.

What do you think about it?

**Comment by gousaiyang** [comment]
I believe they are already parsed to `Param`:

```python
In [17]: import parso

In [18]: parso.__version__
Out[18]: '0.8.2'

In [19]: parso.parse('''\
    ...: def function_with_mandatory_named_params(param: str, *, kw_param: int):
    ...:     pass
    ...: ''').children[0].get_params()
Out[19]:
[<Param: PythonNode(tfpdef, [<Name: param@1,41>, <Operator: :>, <Name: str@1,48>])>,
 <Param: PythonNode(tfpdef, [<Name: kw_param@1,56>, <Operator: :>, <Name: int@1,66>])>]
```

Could you check you parso version?

**Comment by namelivia** [comment]
Hello! Wow, that's a fast response, thank you very much.
Yes, all parameters are parsed, sorry if I didn't explain myself correctly, what I'm referring to is to parse the actual `,*,` as a parameter, so in the function of the example, the parameter count would be 3 instead of 2.

The only reason I would like to do this would be to separate what comes before and what comes after the start, because now (I may be wrong) once you get the list of parameters there is no way to know which are keyword-only parameters.

**Comment by davidhalter** [comment]
Why is there no way to know?

**Comment by gousaiyang** [comment]
If you want to know which are keyword-only parameters, you can iterate through the children list instead of using `get_params()`:

```python
In [23]: parso.parse('''\
    ...: def func(pos_only, /, both, *, kw_only):
    ...:     pass
    ...: ''').children[0].children[2].children
Out[23]:
[<Operator: (>,
 <Param: <Name: pos_only@1,9>>,
 <Operator: />,
 <Operator: ,>,
 <Param: <Name: both@1,22>>,
 <Operator: *>,
 <Operator: ,>,
 <Param: <Name: kw_only@1,31>>,
 <Operator: )>]
```

Changing `get_params()` to return such "virtual" params like `*` is a behavior change of the public API, so we are unlikely to do it unless it brings us significant benefits. Typically looking through the children list is the way to work with concrete syntax trees (CST).

**Comment by davidhalter** [comment]
Agreeing with @gousaiyang here. This is very unlikely to happen because it would change the API. And as he has shown you, there is a way to determine the order. IMO that's good enough, even though it is tedious.

**Comment by namelivia** [comment]
Fair enough! Thanks both for the help and fast answers here :bow:
