### ISSUE TITLE
Falsly marking a starred assignment as SyntaxError

### ISSUE THREAD

**Issue by statist32** [davidhalter/parso#198]
I am using VS Code and encountered this:

`SyntaxError: starred assignment target must be in a list or tuplejedi`

While using the following code example:
`[*return_a_list()]`

The code works because I am returning a list but the part is highlighted red.

**Comment by davidhalter** [comment]
Moved over to parso. We should probably check if this is still an issue with master.

**Comment by davidhalter** [comment]
This is probably not an issue anymore with latest Jedi/Parso, but might still be in not released parso.

>>> import jedi
>>> jedi.Script('[*return_a_list()]\n').get_syntax_errors()
[]
>>> jedi.__version__
'0.18.0'
>>> parso.__version__
'0.8.2'
```

Both are master though.

**Comment by davidhalter** [comment]
This fails in 0.7.0, but not in newer parso versions. You can probably just upgrade it.
