### ISSUE TITLE
incorrect path string syntax

### ISSUE THREAD

**Issue by fuljo** [davidhalter/parso#20]
https://github.com/davidhalter/parso/blob/4824534f8a61746fd8235e7ae9deba3b619ac943/parso/grammar.py#L260

`'python/grammar%s%s.txt'` does not work on all OS (e.g. Windows)
you should use
`os.path.join('python', 'grammar%s%s.txt' % (version_info.major, version_info.minor))` instead

Hope this is helpful.

**Comment by davidhalter** [comment]
Hi fuljo, thanks for that one. It actually works on Windows. But I think we should fix it anyway!
