### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [davidhalter/parso#202]
Hey there!

I belong to an open source security research community, and a member (@ning1022) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by isidentical** [comment]
@JamieSlome can you verify the issue in this context is not related to #75. If it is, then see #75 and #172.

**Comment by JamieSlome** [comment]
@isidentical - I do not believe it is related at first glance - you can find the report here:

https://huntr.dev/bounties/02ef57f1-3098-43f4-b52e-6293eaca3483/

**Comment by isidentical** [comment]
I can't seem to check the report (probably it doesn't see my account as maintainer), cc: @davidhalter in this case.

**Comment by davidhalter** [comment]
Sorry, but I don't sign up for random services. If you need to contact me, please use my email (see profile). I highly doubt that there is a security issue here beyond what @isidentical mentioned. I do not think a `SECURITY.md` file is necessary.

I probably wouldn't mind full disclosure either in this case BTW.

**Comment by JamieSlome** [comment]
@davidhalter - I have made the report fully visible for you 👍 

https://huntr.dev/bounties/02ef57f1-3098-43f4-b52e-6293eaca3483/

**Comment by isidentical** [comment]
I have no idea about how this is even close to a security issue. If you feed the parser with invalid input (this includes these sort of non-decodable objects) it will throw an error. I don't see any way of this getting abused from directly parso's side, since handling of such errors is the responsibility of the client. See `ast.parse()` which would the exact same thing for this sort of input.

**Comment by davidhalter** [comment]
Thanks Jamie.

-----

Yes. I don't even understand how anyone could think a `UnicodeDecodeError` was going to lead to a denial of service. If anything this would just be a normal bug. However it is intentional that non-utf8 throws an error there anyway.

**Comment by JamieSlome** [comment]
@davidhalter - thanks for the feedback nonetheless!
