### ISSUE TITLE
Question: How to integrate it to vim?

### ISSUE THREAD

**Issue by moylop260** [davidhalter/parso#21]
Hello
This tools is great
Thanks

Is posible a integration with vim?

**Comment by davidhalter** [comment]
Like how? It's a parser. It's supposed to be used by libraries to do something. The libraries might then be used within VIM. However I don't even see use cases where parso would be used just with VIM. parso is used by jedi, which is used by jedi-vim - which is a VIM plugin. So there you go, that's the integration ;)
