### ISSUE TITLE
Any plan to support Python 3.11+

### ISSUE THREAD

**Issue by wenijinew** [davidhalter/parso#213]
Hi,
Now, I am having this problem, do you happen to have any plan to support Python 3.11+?
`../python3.11/site-packages/parso/grammar.py", line 256, in load_grammar
raise NotImplementedError(message)
NotImplementedError: Python version 3.11 is currently not supported.
`

**Comment by davidhalter** [comment]
grammar311 and 312 exist. So you are probably on an older version.

**Comment by wenijinew** [comment]
Yes, it is. Thanks

The latest version of python-language-server is 0.36.2 which requires the version of jedi and parso.

python-language-server 0.36.2 requires jedi<0.18.0,>=0.17.2
jedi 0.17.2 requires parso<0.8.0,>=0.7.0
