### ISSUE TITLE
Feature request: Support Python 3.13

### ISSUE THREAD

**Issue by rajeeshknambiar** [davidhalter/parso#226]
YouCompleteMe doesn't autocomplete with Python 3.13 and the debugging showed this in the log (`tail -f /tmp/ycmd_42337_stderr_sefw9rcr.log`):
```python
$HOME/.vim/pack/plugins/opt/YouCompleteMe/third_party/ycmd/third_party/jedi_deps/parso/parso/grammar.py", line 264, in load_grammar
    raise NotImplementedError(message)
NotImplementedError: Python version 3.13 is currently not supported.
```
Feature request to support Python 3.13, thanks!

**Comment by davidhalter** [comment]
I literally released a new Jedi version yesterday.
