### ISSUE TITLE
Travis Itself Fails

### ISSUE THREAD

**Issue by MohamedAlFahim** [davidhalter/parso#28]
> Invocation failed (exit code 1), logfile: /home/travis/build/davidhalter/parso/.tox/py33/log/py33-1.log

Check out the RecursiveChildPrinter pull request for more information.

Generally speaking, the testing method is failing itself, causing an overall build failure.

**Comment by davidhalter** [comment]
Yes, I need to fix travis for 2.6 and 3.3. I have no idea why it still works in Jedi and not in parso...

**Comment by davidhalter** [comment]
Fixed it! Thanks.
