### ISSUE TITLE
An option to disable cache completely

### ISSUE THREAD

**Issue by KOLANICH** [davidhalter/parso#32]
This cache takes a lot of space. I guess I'm ready to trade some speed for not having this eating space on my HDD. I guess there should be a global config file for parso and jedi where I should be able to disable caching completely.

**Comment by davidhalter** [comment]
There is a global setting within jedi: `jedi.settings.use_filesystem_cache`.

For parso there is no global setting, but in each parso call you can enable/disable the cache with a parameter.

**Comment by KOLANICH** [comment]
Thank you for the info.
