### ISSUE TITLE
Enable to disable LOG.Debug

### ISSUE THREAD

**Issue by giangm9** [davidhalter/parso#34]
I embed IPython in [blender](https://www.blender.org/), when I type a variable name and ' 'tab', parso's debug log shows up and this so annoying 
```
In [1]: armDEBUG:THREE:pickle loaded: /home/gl/tools/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/modules/bpy_types.py
atureDEBUG:THREE:diff parser start
DEBUG:THREE:diff parser calculated
DEBUG:THREE:diff: line_lengths old: 1, new: 1
DEBUG:THREE:diff replace old[1:1] new[1:1]
DEBUG:THREE:parse_part from 1 to 1 (to 0 in part parser)
DEBUG:THREE:diff parser end
```
My current solution is remove log from source code file. I think there is must be a better way to disable Logs

**Comment by davidhalter** [comment]
Disabling logs is possible with the builtin `logging` module. It's actually not that hard, just search for it. They might need to fix this inside the blender Python plugin, but that's all. 

You can also disable specific logs to avoid disabling everything (e.g. just disable parso).

This should usually work:

```
        root = logging.getLogger('parso')
        root.setLevel(logging.INFO)
```

**Comment by Granitosaurus** [comment]
While setting level manually works I don't think it should be default on debug level. This is very unusual and creates all sorts of problems like the one described in OP.

This completely breaks `ptpython` shell as described in https://github.com/jonathanslenders/ptpython/issues/241

**Comment by Granitosaurus** [comment]
:point_up: PR to fix this
