### ISSUE TITLE
Improve Unicode name matching regex

### ISSUE THREAD

**Issue by ambv** [davidhalter/parso#36]
Great that you're already matching Unicode names! However, looks like you're currently simply accepting one-or-more characters of class `w`:
```py3
Name = r'\w+'
```
AFAICT, a better regex for this would be:
```py3
Name = r'[^\d\W]\w*'
```

**Comment by ambv** [comment]
Context: class `w` includes digits that can't start identifiers.

**Comment by davidhalter** [comment]
AFAIK This was pulled out of CPython (probably something like 3.3). It seems to work great currently, because the regex group matches numbers first.

**Comment by davidhalter** [comment]
I just checked again and this still matches CPython 3.6 as well as master. So I guess I'll leave it the way it is, because it's the same there.

Thanks for looking over the code though and trying to fine issues!

**Comment by ambv** [comment]
It doesn't match master lib2to3. Master lib2to3 doesn't support Unicode identifiers at all yet. I'll be doing that soon.

**Comment by davidhalter** [comment]
Interesting. I kind of forgot that lib2to3 runs its  own implementation of tokenize.py. IMO that redundancy could also be reduced. I usually just look at the changes in the "official" tokenize.py.

**Comment by ambv** [comment]
> "official" tokenize.py
You mean tokenizer.c?

The builtin CPython tokenizer accepts "whatever" as a name but later it runs the identifier through `verify_identifier()` which performs the PyUnicode_IsIdentifier check (you can find that in Objects/unicodeobject.c). That check does the full PEP 3131 verification of the first character and the rest.

For lib2to3 I won't implement the entire PEP 3131 check because frankly it's annoyingly complex. The regex I suggested above is "good enough" in that it's missing a relatively small number of code points (notably the legacy Other_ID_Start and Other_ID_Continue groups). To be closer to PEP 3131, I further verify [the initial character is in allowed classes](https://github.com/ambv/black/blob/master/blib2to3/pgen2/tokenize.py#L509-L510).

**Comment by ambv** [comment]
Oh, you actually meant `tokenize.py` in the stdlib. I on the other hand always forget about *this* one since it's relatively obscure. It's used mostly via `linecache`, otherwise only `inspect`, `imp` and `IDLE` depend on it.

**Comment by davidhalter** [comment]
> I on the other hand always forget about this one since it's relatively obscure.

I can understand that, but then again it's what all the devs are using out there if they want to tokenize Python code. Most people don't even know there's a parser generator (and another tokenizer) in lib2to3.

In the long term it could even be interesting to make the tokenizer.c one public with some simple Python mappings. It's probably quite a bit faster and definitely closer the closest to what's actually happening in Python.

AFAIK https://www.python.org/dev/peps/pep-3131/ is already implemented (even in lib2to3). There's an `isidentifier` check that essentially does exactly the same thing as `verify_identifier`. The only thing I haven't properly done is implement all the `ASYNC`/`AWAIT` differentiation when in function and when not. That's something we can still do if we want, but I was basically to lazy and thought that Python 3.7 behavior is fine for most people.

Did you even see that you can check your CST for validity with parso? Might come in handy with something like black.
