### ISSUE TITLE
dead code in `get_definition()`

### ISSUE THREAD

**Issue by thisfred** [davidhalter/parso#4]
this if condition is always false, so the branch never executes:

https://github.com/davidhalter/parso/blob/dcdd3bbc8e2432006ccd9b3c565441885e38af57/parso/python/tree.py#L217-L220

(this may be intentional or temporary, I'm not sure there's an actual bug here, but I found this while investigating a case where variables that occur within a function are not finding their definition within the same function body.)

**Comment by thisfred** [comment]
Also, thank you for splitting this out, it looks like a fantastic library! :)

**Comment by davidhalter** [comment]
Obviously those lines are not needed. Thanks :)

> Also, thank you for splitting this out, it looks like a fantastic library!

I appreciate that!!
