### ISSUE TITLE
Don't mutate the token.tok_name dictionary

### ISSUE THREAD

**Issue by asmeurer** [davidhalter/parso#41]
The parso `token` library takes the standard library `token.tok_name` dictionary and mutates it [here](https://github.com/davidhalter/parso/blob/a91e5f277564a1e4f535ed463e358efd67531697/parso/python/token.py#L21). 

This results in some very odd behavior when using `tokenize` in my Python shell that uses Jedi. Before I do any tab completions, things work just fine. But as soon as I do a tab completion, parso is imported, and `ENCODING` is replaced with `BACKQUOTE`. 

Parso should instead use its own copies of mutable data structures and leave the standard library alone.

**Comment by davidhalter** [comment]
You're 100% right. This is a pretty serious bug.

**Comment by asmeurer** [comment]
I think a simple `tok_name = tok_name.copy()` at the top of the file should do the trick. Everything else in [token](https://github.com/python/cpython/blob/master/Lib/token.py) is immutable, so it shouldn't be an issue, though I personally would replace the `from token import *` with `import token` or `from token import ...`.

Also worth noting that `N_TOKENS` does account for `COMMENT`, `NL` and `ENCODING` in Python 3.7.

**Comment by davidhalter** [comment]
I'm not 100% sure how to fix the last things you mentioned. I'd happily accept a PR. Otherwise I'll do it myself in the next couple of weeks.

**Comment by asmeurer** [comment]
Never mind. I'm just saying you could avoid `import *`. But it doesn't matter.

**Comment by asmeurer** [comment]
By the way, I discovered you're not the [only one](https://github.com/xonsh/xonsh/issues/2671) doing this.

**Comment by davidhalter** [comment]
Yeah the star import could be avoided. I agree. I was and am probably just too lazy to change it.
