### ISSUE TITLE
question: what's your timeline for supporting new python versions?

### ISSUE THREAD

**Issue by njsmith** [davidhalter/parso#47]
In [this PR](https://github.com/python-trio/trio/pull/594), we're trying to write a test that uses jedi. The overall project tests against 3.8-dev, but of course trying to use jedi under python 3.8 currently [errors out](https://travis-ci.org/python-trio/trio/jobs/419421251) with:

```
E                   FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/parso/python/grammar38.txt'
```

Totally reasonable, and we can skip the test on 3.8 for now.

But... I don't want to just mark the test as skipped on Python 3.8, because then it'll remain skipped and forgotten forever, past when 3.8 comes out :-).

Do you have a usual timeline for adding grammars for new python releases? For example, we could mark the test as skipped until 3.8-beta is released, or 3.8-final...

**Comment by davidhalter** [comment]
If you want you can just add a PR for the Python 3.8 grammar. I don't think anything has change from 3.7 and once it will we can just change the grammar file. There's nothing more you need to do.

**Comment by davidhalter** [comment]
For Jedi it's a bit more complicated. 3.7 support is not really out yet and I'm still working on that. However once 3.7 (for Jedi is supported we can probably also support 3.8-dev.

**Comment by davidhalter** [comment]
Python 3.8 has been added.
