### ISSUE TITLE
Escaped quotes produce incorrect SyntaxError in f-strings

### ISSUE THREAD

**Issue by PythonNut** [davidhalter/parso#48]
I think I've found a small issue with quote escaping in `f-strings`. Consider the following code:
```python
import parso
s = "f\"\\\"\""
eval(s) # this works
grammar = parso.load_grammar()
module = grammar.parse(s)
(err,) = grammar.iter_errors(module)
print(err.message)
```
The `eval` call works fine (and produces `"` as expected), while the `err.message` is:

> SyntaxError: EOL while scanning string literal.

This is with:

* `python 3.7`
* `parso 0.3.1`

**Comment by davidhalter** [comment]
Thanks for finding this one!

**Comment by boxed** [comment]
A simpler reproduction scenario is just

'\''

**Comment by sbeland** [comment]
Hi @davidhalter! Is there an ETA on a fix for this issue?

**Comment by davidhalter** [comment]
@sbeland I'm probably going to fix it this month. I'm working on parso quite a lot these days (I have written a fuzzer that finds a lot of issues).

In general I'm wondering what you guys are using `iter_errors` for?! I have not seen it being used in the wild.

**Comment by PythonNut** [comment]
I use it in https://github.com/PythonNut/reloadr-parso, (fork https://github.com/hoh/reloadr to swicth from RedBaron to parso).

**Comment by boxed** [comment]
I just discovered I actually have this issue with the code base at work!

**Comment by davidhalter** [comment]
Fixed it. Release coming soon. Please let me know if it's still an issue.

@sbeland: I'd still be interested what you're using it for, even if it's for work.
