### ISSUE TITLE
Duplicate statements in `KeywordStatement` docstring

### ISSUE THREAD

**Issue by Hoboneer** [davidhalter/parso#55]
Specifically this part of the docstring repeats a pair at the end:

```For the following statements: `assert`, `del`, `global`, `nonlocal`, `raise`, `return`, `yield`, `return`, `yield`.```

`return` and `yield` are repeated, but I'm not sure what is meant to be in their place (if any). Someone more knowledgeable than I am about the Python grammar would be able to create a fix.

**Comment by davidhalter** [comment]
Thanks.
