### ISSUE TITLE
Possibly incorrect line at parso/python/pep8.py:148

### ISSUE THREAD

**Issue by MiguelLatorre** [davidhalter/parso#6]
I was looking at some of the new parso library just for fun and I found:
```
def _is_magic_name(name):
    return name.value.startswith('__') and name.value.startswith('__')
```
I guess the intention is 
```
def _is_magic_name(name):
    return name.value.startswith('__') and name.value.endswith('__')
```

i.e.: "endswith" instead of repeating "startswith". :)

Good library by the way, keep it up! I use jedi-vim every day!!

**Comment by davidhalter** [comment]
Oh wow. Thanks a lot!
