### ISSUE TITLE
Parsing integer literals with 'L' or 'l' suffix results in error nodes in Python 2 grammars

### ISSUE THREAD

**Issue by adam-kucz** [davidhalter/parso#65]
Minimal example

`parso.load_grammar(version='2.7').parse("n = 1L").children`

results in

`[<PythonErrorNode: n = 1@1,0>,
 <Name: L@1,5>,
 <EndMarker: prefix='' end_pos=(1, 6)>]`

but it is valid Python 2 code

**Comment by davidhalter** [comment]
Oh wow, I forgot about those :)

**Comment by davidhalter** [comment]
Fix in #72. I'm going to merge that once the small remaining issues are resolved.
