### ISSUE TITLE
Abnormal behavior when using get_defined_names

### ISSUE THREAD

**Issue by DennielZhang** [davidhalter/parso#66]
Hi,

I found that when I use `get_defined_names` for a atom_expr object, it just don't wok.

Then atom_expr code that I used to test is below:
```python
detections['detection_masks'] = tf.to_float(
          tf.greater_equal(tf.sigmoid(mask_predictions), mask_threshold))
```
I thought it will return me `detections['detection_masks]` after `get_defined_names`, but it returns nothing.

I checked your codes in `get_defined_names` and `_defined_names`. I found that you handle it like this:
```python
elif current.type in ('power', 'atom_expr'):
        if current.children[-2] != '**':  # Just if there's no operation
            trailer = current.children[-1]
            if trailer.children[0] == '.':
                names.append(trailer.children[1])
```
So, you just add to `names` only if it looks like `xx.xxx`. So I just want to ask why don't you consider situation that I met and how you define `defined_name`.

Thanks!

**Comment by davidhalter** [comment]
I might need to document this better, but `get_defined_names` is only there for names that are newly defined, in your example no name was defined, a dictionary was modified. This is also possible with `detections.update(detection_masks=foo)`, which does exactly the same but has also no defined name, it only calls `__setitem__`.

So I would argue that this works correctly.

**Comment by davidhalter** [comment]
Let me know if this is not a good enough explanation for you.

**Comment by davidhalter** [comment]
I decided to make this possible when setting `get_defined_names(include_setitem=True)`.
