### ISSUE TITLE
Support for adding and removing nodes in the parsed tree

### ISSUE THREAD

**Issue by mkurnikov** [davidhalter/parso#67]
I'm working on support for this for `isort` now in their repo. If/when I finish, I'll try to make a PR to `parso` itself. 

I would like to have a functionality to:
1. Add/remove node (adjusting `start_pos` of nodes for subsequent nodes). 
2. Add/remove lines (same thing).

**Comment by davidhalter** [comment]
Hi @mkurnikov 

There will not be exactly what you want, but something similar :) What we can support is something similar that has a new tree as its output. I learned at one point that it's a pretty bad idea to mutate the datastructure of the parser tree.

What we can do however is output a new tree - copy the old one and create a new tree.

**Comment by mkurnikov** [comment]
I'm actively working with the library now and have a couple of questions, if you don't mind. 

1. It seems that only data that used in the `get_code()` method is `value`, `prefix` and parent-child relationships in the FST. So, for final deserialization, `start_pos` makes no difference, right? 

Also, it looks like `start_pos` could be recomputed at any time from the root, all data is there, is this correct? Could we add a method like `refresh_positions()` for this purpose? And with that, there's no need to make it a required parameter in the `Leaf` contructor 
https://github.com/davidhalter/parso/blob/master/parso/tree.py#L170

2. Why there's no assignment of children's `parent` in the `BaseNode` contructor
https://github.com/davidhalter/parso/blob/master/parso/tree.py#L251
like, 
```
for child in children:
    child.parent = self
```
Does this piece of functionality makes no difference for `get_code` too, and serves only as an information for the user? Still, wouldn't it be better to add it there?

**Comment by mkurnikov** [comment]
If those observations are correct, then
1. `start_pos` could be removed from constructor
2. `children` attribute could be converted into `@property`, and we could add method to `BaseNode`
```
def insert_child(node):
    ...
```
which will check whether child node already has a parent, set proper parent-child relationships, and recompute `start_pos` attributes for the whole tree. 

This could lay good foundation for the refactoring operations on top of `parso` FST.

**Comment by davidhalter** [comment]
> Why there's no assignment of children's parent in the BaseNode contructor
> ...

Immutable objects are better than mutable objects. The code was actually like you described and after hours searching for a bug, I realized that was to blame. If you initialize something like `Function(children_nodes)`, you don't expect the `Function` to modify anything in `children_nodes`. That's why it's bad to write code like that. It's better to create a separate function:

```
def create_node_with_updated_parents(cls, children):
    new_node = cls(children)
    for child in children:
        child.parent = new_node

...

create_node_with_updated_parents(Function, [...]))
```

> Does this piece of functionality makes no difference for get_code too, and serves only as an information for the user?

It doesn't make a difference. For get_code only prefix, value and children are relevant.

> It seems that only data that used in the get_code() method is value, prefix and parent-child relationships in the FST. So, for final deserialization, start_pos makes no difference, right?

Yes, this is true. It's a round-trip parser-tree, so positions are just cached. Also what's an FST?

> Also, it looks like start_pos could be recomputed at any time from the root, all data is there, is this correct? Could we add a method like refresh_positions() for this purpose? And with that, there's no need to make it a required parameter in the Leaf contructor

> 2. children attribute could be converted into @property, and we could add method to BaseNode
> 
> def insert_child(node):
>     ...
> 
> It is required in the Leaf constructor for performance reasons.
> ...
> 
> This could lay good foundation for the refactoring operations on top of parso FST.

As I said, the parser tree is not going to be modified. That's a bad idea. Trust me, it's not the first iteration of this parser, it's about the 6th and the only thing that I have consistently learned that mutable data structures are really really dangerous. So no officially supported mutability, I will not shoot myself in the head.

What we should do instead is use something like `normalizers`. A normalizer takes a parsed tree and transforms it into a new tree or typically just code. Don't be scared by the name, it's just the name in parso for this kind of behavior.

Consider this code:

```
grammar = load_grammar()
tree = grammar.parse(path=some_file)
normalizer = RefactoringNormalizer(...)
first_leaf = tree.get_first_leaf()
normalizer.replace_leaf(first_leaf, prefix='#first_line_comment\n' + first_leaf.prefix)

new_code = normalizer.walk(tree)
# Now do whatever with this new code
```

What does this piece of code do? It adds a comment in the beginning of the file. This is ideally what I want to do: I want to change code without actually modifying the parse tree.

How would the implementation of the normalizer look like? Probably something like this:

```
from parso.normalizer import Normalizer

class RefactoringNormalizer(Normalizer):
    def __init__(self):
        super(RefactoringNormalizer, self).__init__()
        self._replaced_leaves = {}

    def replace_leaf(self, leaf, prefix=None, value=None):
        self._replaced_leaves[leaf] = prefix, value

    def visit_leaf(self, leaf):
        try:
            prefix, value = self._replaced_leaves[leaf]
            return leaf.prefix if prefix is None else prefix \
                + leaf.value if value is None else value
        except KeyError:
            return leaf.prefix + leaf.value
```

Of course there could be more methods than `replace_leaf`. But this feels like a good abstraction for refactoring.

**Comment by mkurnikov** [comment]
> FST

Full Syntax Tree. Sorry, I thought it's established term, got it from RedBaron mentions here https://github.com/oilshell/oil/wiki/Lossless-Syntax-Tree-Pattern

> As I said, the parser tree is not going to be modified. That's a bad idea. Trust me, it's not the first iteration of this parser, it's about the 6th and the only thing that I have consistently learned that mutable data structures are really really dangerous. So no officially supported mutability, I will not shoot myself in the head.

Ok, I agree. I was just scared a bit by the amount of work needs to be done for parso to implement immutable tree changes, manually setting children feels simpler. 

> normalizers

I didn't know that parso already has that kind of functionality, thanks! I like the idea of a higher level "transformer" entity on top of parsed tree, I'll check it out and get back to you later.

**Comment by davidhalter** [comment]
Awesome! Have fun :)

I get that it's easier to mutate the tree, but I guarantee once we have a good normalizer it will be even more fun, because we can create multiple tranformations on the same tree :)

**Comment by marcglobality** [comment]
Hi @davidhalter , it looks like the `RefactoringNormalizer` made it to the final code, but it's not in the documentation. Could you rewrite your example with the final version? There's no `replace_leaf` in there. Plus, I'm not sure what to pass as `config`.

My use case is the following:

I want to replace
```
def foo(
    arg1="marc", arg2=" at ", arg3="globality",
):
    return arg1 + arg2 + arg3
```
to
```
def foo(
    arg1="marc", 
    arg2=" at ", 
    arg3="globality",
):
    return arg1 + arg2 + arg3
```

any hints?

Thanks!

**Comment by davidhalter** [comment]
@marcglobality Sorry I'm too lazy to do that. You will have to do it yourself.
