### ISSUE TITLE
Interest in shipping type annotations with the project?

### ISSUE THREAD

**Issue by carljm** [davidhalter/parso#68]
Hi! Thanks for parso.

We are using parso in a project that uses Python PEP 484 type annotations and a typechecker, so we have written fairly comprehensive type stubs for Parso's API. We'd like to share this work with the community, if you are amenable. There are many options for how to do this:

1) Integrate type annotations directly into the codebase (need to use the comment-based syntax in order to preserve Python2 support). This is perhaps the best in terms of ensuring they stay up to date, but it depends if you want type hint comments in the code.

2) Add `.pyi` stub files next to the `.py` files in the repo. This is next-best for ensuring they stay up to date, but keeps them out of the code for those who don't care.

3) Keep them out of the parso repo entirely and include them in github.com/python/typeshed instead. This is the best option if you don't want to adopt any responsibility for maintaining them, and leave it up to the users of parso and typecheckers. But we won't do this either without your permission.

Let me know if any of those options sound acceptable to you, and which you prefer! Thanks again for your work on parso.

**Comment by davidhalter** [comment]
Hi @carljm 

Just wondering: What are you using parso for? I'm always interested about that :)

I personally prefer pyi stub files. I'm of course all for integrating them in the code base (and maybe even let mypy or another type checker check it), but at the same time I dislike type comments very much.

They age so quickly. It's only one year until Python 2 support is going to be dropped, now. I'm probably going to drop Python 2.7 support early 2021 so that would mean that I have to remove all the type comments again.

~ Dave

**Comment by carljm** [comment]
Hi @davidhalter - thanks for the quick response!

We are working on a Concrete Syntax Tree for Python with a higher-level typed API (similar to the AST module, with separate node types for all syntactic elements), to make it easier to write automated transformations of Python code. This work isn't public right now but we hope to share it at some point. We are building on top of parso to handle the parsing.

Your preference makes sense! I'll submit a PR for type stubs next to the code. I think if we are taking that approach, it isn't super valuable to run a typechecker over it, since all it will test is well-formedness of the stubs. The stubs will "shadow" the real code from the typechecker's perspective, so no implementation code will actually be checked.

**Comment by carljm** [comment]
Pull request in #69 .

**Comment by davidhalter** [comment]
PR was merged.

**Comment by jimmylai** [comment]
To empower type checker to use the added type annotation. We need to either include the stub files in parso package or release a stub only package.
Mypy doc provides more detail.
https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages
Which way do we prefer?

**Comment by carljm** [comment]
Given that stub files are already in the repo, it seems there's no reason not to include them in the main release package? My PR should have included that but didn't :/ Having a separate stubs package just means more releases to make. Non-users of typing aren't hurt by the inclusion of stub files in the package.

**Comment by davidhalter** [comment]
@carljm I agree.

**Comment by jimmylai** [comment]
Created PR #81 as follow up.
