### ISSUE TITLE
No grammar for Python 3.7

### ISSUE THREAD

**Issue by thorstenkampe** [davidhalter/parso#7]
Using IPython 6.2 with Python 3.7.0a1 (early adopter so to say), I get an error when trying to tab-complete which refers to a missing grammar text file. Copying the grammar for 3.6 to 3.7 resolves the problem.

Could you deliver a preliminary grammar for Python 3.7 by using the grammar from Python 3.6?

**Comment by dimaqq** [comment]
Me too!

**Comment by davidhalter** [comment]
Just add a pull request. I'll happily merge.
