### ISSUE TITLE
Python 3.7 deprecation warning on collections.Mapping import

### ISSUE THREAD

**Issue by pquentin** [davidhalter/parso#76]
Since https://github.com/davidhalter/parso/commit/3fa8630ba9824aee3dc5f769d8fb56034890cb94, parso uses `from collections import Mapping`, but that's deprecated since Python 3.7:

`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

The plan is now to remove this starting with Python 3.9: https://docs.python.org/3.8/library/collections.html, but that still issues a warning on Python 3.7, and we [fail our test suite on warnings](https://github.com/python-trio/trio/pull/1120:). Since parso stills supports Python 2, I guess the fix looks like this (untested):

```
try:
    from collections.abc import Mapping
except ImportErrror:
    from collections import Mapping
```

Thanks!

**Comment by davidhalter** [comment]
Will be part of the next release. I hope you don't need it "now".

**Comment by pquentin** [comment]
Waiting for the next release is fine! dependabot will open a new PR automatically when that happens, so really there's nothing urgent

**Comment by pquentin** [comment]
Oh, and thank you for the quick fix!
