### ISSUE TITLE
Dates wrong in changelog?

### ISSUE THREAD

**Issue by sedm0784** [davidhalter/parso#77]
Versions 0.3.2 through 0.3.4 were added to the [GitHub releases page](https://github.com/davidhalter/parso/releases) in 2019, but are listed in [`CHANGELOG.rst`](https://github.com/davidhalter/parso/blob/master/CHANGELOG.rst) with dates in 2018. Are the dates in the changelog wrong?

**Comment by davidhalter** [comment]
Thanks for seeing that!
