### ISSUE TITLE
Replace pickle cache files with a file-format without code execution

### ISSUE THREAD

**Issue by davidhalter** [davidhalter/parso#79]
Having pickle as a serialization format is not the best pick for a cache (for parso's case). However it seems like there aren't really a lot of "fast" alternatives in the standard library.

This issue is also related to #75.

**Comment by hartwork** [comment]
Have you looked into `msgpack` for an alternative?
https://github.com/msgpack/msgpack-python#one-shot-pack--unpack

**Comment by davidhalter** [comment]
While I agree that msgpack might be interesting, I just don't consider it important enough to add an additional dependency. However thanks for bringing it to my attention @hartwork. I think it is indeed a very interesting library. The performance seems also good: https://medium.com/@shmulikamar/python-serialization-benchmarks-8e5bb700530b. 

Closing, because there is no good/fast alternative in the CPython standard library.
