### ISSUE TITLE
Question: Is it possible to edit code with this library?

### ISSUE THREAD

**Issue by jack1142** [davidhalter/parso#96]
Hi, I'm sorry that I'm asking a question through issue, but I didn't see any other way to ask questions about this lib in README. 

So, I'm looking at docs and it isn't obvious if I can edit code with this library or is this library only for analysing code without making any changes to it? I've been looking for an alternative to `redbaron` (and underlying `baron`) that is more maintained and this library has been mentioned in few places but docs don't really mention editing so I'm not sure if that's possible with this library.

Whatever the answer will be, thank you for this library, Python really needs good syntax parsers.

**Comment by davidhalter** [comment]
@jack1142 It is mentioned that Parso is round-trippable which is what you mean by editing code.

This means you can make edits in the syntax tree and use `.get_code()` to return the modified code.

At the moment I think this side effect on the syntax tree is a bad idea if you work with caching. So just don't use caching if you plan to edit a syntax tree. I have ideas how to improve that, but it will take a while and https://github.com/davidhalter/jedi/issues/667 will probably be the trigger for me to do that.

But in the mean time, just modifying the syntax tree will suffice (as long as you don't use parso's caching mechanisms).

I'm closing, but feel free to keep asking questions, I will still answer.

**Comment by jack1142** [comment]
@davidhalter I looked at the docs to find out what caching you're talking about but I see it's disabled by default, so I'll just assume that I don't need it as performance isn't a worry for me here anyway.

Let me bring an example I'm particularly interested in figuring out right now. I want to find a class with name X and either modify its docstring if it already exist, or add it if it doesn't.
If docstring already exists, this looks easy:
<details>
<summary>Example 1</summary>

```py
source = '''
class Example:
    """Test docstring."""
    
    def __init__(self, x):
        self.x = x
'''

tree = parso.parse(source)
# I should loop through those and check name, but this is simplified example
class = list(tree.iter_classdefs())[0]

docstring = class.get_doc_node()
assert docstring is not None
docstring.value = '"""Modified docstring."""'

print(tree.get_code())

# Output
assert source == '''
class Example:
    """Modified docstring."""

    def __init__(self, x):
        self.x = x
'''
```
</details>

However, if docstring doesn't exist, I would need to create a String node and put it into class's scope, and I don't really know which attributes/methods I should look at:
<details>
<summary>Example 2</summary>

```py
source = '''
class Example:
    def __init__(self, x):
        self.x = x
'''

tree = parso.parse(source)
# I should loop through those and check name, but this is simplified example
class = list(tree.iter_classdefs())[0]

docstring = class.get_doc_node()
assert docstring is None
# Okay, there is no docstring, how should I add it?


# Expected output
assert source == '''
class Example:
    """Added docstring."""

    def __init__(self, x):
        self.x = x
'''
```
</details>

**Comment by davidhalter** [comment]
In that case you take the first token of the `suite` (see Python grammar). It's essentially something like

```
first_leaf = class_node.children[-1].get_first_leaf()
first_leaf.prefix = ...
```

Obviously you need to care about whitespace around the docstring yourself. If you don't want to do that, you can also use `first_leaf._split_prefix()`, which is private for now, but it can help. It might just change in the future without a warning.
